import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { X, GitBranch, CheckSquare, Square, FileText, ExternalLink, ShieldCheck, Award, ArrowRight, Upload } from 'lucide-react';
import { translations } from '../data/translations';

export default function SchemeDetailModal({ scheme, onClose, language }) {
  const navigate = useNavigate();
  if (!scheme) return null;
  const t = translations[language] || translations.EN;

  // Track checked document status
  const [checkedDocs, setCheckedDocs] = useState({});

  const toggleDoc = (docId) => {
    setCheckedDocs(prev => ({
      ...prev,
      [docId]: !prev[docId]
    }));
  };

  const totalDocs = scheme.documents ? scheme.documents.length : 0;
  const completedDocs = scheme.documents ? scheme.documents.filter(d => checkedDocs[d.id]).length : 0;
  const completionPercentage = totalDocs > 0 ? Math.round((completedDocs / totalDocs) * 100) : 0;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-fadeIn">
      <div className="bg-surface-container-lowest border border-outline-variant rounded-3xl shadow-2xl w-full max-w-4xl max-h-[90vh] overflow-y-auto p-6 md:p-8 space-y-6">
        
        {/* Header */}
        <div className="flex items-start justify-between gap-4 border-b border-outline-variant/40 pb-4">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <span className="px-2.5 py-0.5 rounded-full text-xs font-bold bg-primary/10 text-primary">
                {scheme.govtLevel}
              </span>
              <span className="text-xs text-on-surface-variant font-medium">{scheme.category}</span>
            </div>
            <h2 className="text-2xl font-extrabold text-on-surface">{scheme.name}</h2>
          </div>

          <button
            onClick={onClose}
            className="p-2 rounded-full hover:bg-surface-container text-outline hover:text-on-surface transition-all cursor-pointer"
          >
            <X className="w-6 h-6" />
          </button>
        </div>

        {/* Financial Benefit Header Banner */}
        <div className="bg-gradient-to-r from-primary to-primary-container text-white p-5 rounded-2xl flex flex-wrap items-center justify-between gap-4 shadow-md">
          <div>
            <span className="text-slate-300 text-xs font-bold uppercase tracking-wider block">Financial Assistance / Benefit</span>
            <span className="text-2xl font-black text-saffron">{scheme.benefitAmount}</span>
          </div>

          <div className="flex items-center gap-2 bg-white/10 px-3.5 py-2 rounded-xl text-xs font-bold">
            <Award className="w-4 h-4 text-emerald-400" />
            <span>AI Policy Match: {scheme.matchScore || 95}%</span>
          </div>
        </div>

        {/* Section 1: Interactive Decision Tree Graph */}
        <div className="bg-surface-container-low/50 border border-outline-variant/60 rounded-2xl p-5 md:p-6 space-y-4">
          <div className="flex items-center gap-2">
            <GitBranch className="w-5 h-5 text-saffron" />
            <h3 className="text-base font-bold text-on-surface">{t.decisionTreeTitle}</h3>
          </div>
          <p className="text-xs text-on-surface-variant">
            Visual rule evaluation path generated by BharatAI engine based on your profile inputs.
          </p>

          {/* Flowchart Nodes */}
          <div className="grid grid-cols-1 md:grid-cols-4 gap-3 pt-2 relative">
            {scheme.decisionTree.nodes.map((node, idx) => (
              <div
                key={node.id}
                className="relative bg-surface-container-lowest border-2 border-emerald-400 rounded-xl p-4 space-y-1 shadow-sm"
              >
                <div className="flex items-center justify-between">
                  <span className="text-[10px] font-extrabold uppercase text-emerald-700 bg-emerald-100 px-2 py-0.5 rounded-full">
                    Step 0{idx + 1}
                  </span>
                  <span className="w-2.5 h-2.5 rounded-full bg-emerald-500 animate-pulse" />
                </div>
                <div className="font-bold text-xs text-on-surface">{node.label}</div>
                <div className="text-[11px] text-on-surface-variant leading-tight">{node.detail}</div>
              </div>
            ))}
          </div>
        </div>

        {/* Section 2: Document Readiness Tracker */}
        <div className="bg-surface-container-lowest border border-outline-variant/60 rounded-2xl p-5 md:p-6 space-y-4">
          <div className="flex items-center justify-between flex-wrap gap-2">
            <div className="flex items-center gap-2">
              <FileText className="w-5 h-5 text-primary" />
              <h3 className="text-base font-bold text-on-surface">{t.docChecklistTitle}</h3>
            </div>

            <div className="text-xs font-bold text-primary">
              Ready: {completedDocs} / {totalDocs} ({completionPercentage}%)
            </div>
          </div>

          {/* Progress bar */}
          <div className="w-full h-2.5 bg-surface-container-high rounded-full overflow-hidden">
            <div
              className="h-full bg-emerald-500 transition-all duration-300 rounded-full"
              style={{ width: `${completionPercentage}%` }}
            />
          </div>

          <p className="text-xs text-on-surface-variant">{t.uploadNotice}</p>

          {/* Documents Checklist items */}
          <div className="space-y-2.5 pt-1">
            {scheme.documents.map((doc) => {
              const isChecked = !!checkedDocs[doc.id];
              return (
                <div
                  key={doc.id}
                  onClick={() => toggleDoc(doc.id)}
                  className={`flex items-center justify-between p-3 rounded-xl border transition-all cursor-pointer ${
                    isChecked
                      ? 'bg-emerald-50/60 border-emerald-300 text-emerald-950'
                      : 'bg-surface border-outline-variant/60 text-on-surface hover:bg-surface-container-low'
                  }`}
                >
                  <div className="flex items-center gap-3">
                    {isChecked ? (
                      <CheckSquare className="w-5 h-5 text-emerald-600 shrink-0" />
                    ) : (
                      <Square className="w-5 h-5 text-outline shrink-0" />
                    )}
                    <span className="text-xs font-semibold">{doc.name}</span>
                  </div>

                  <div className="flex items-center gap-2">
                    <button
                      type="button"
                      onClick={(e) => {
                        e.stopPropagation();
                        if (onClose) onClose();
                        navigate(`/verify?doc=${doc.id}`);
                      }}
                      className="py-1 px-2.5 bg-primary/10 hover:bg-primary text-primary hover:text-white rounded-lg text-[11px] font-bold transition-all flex items-center gap-1"
                    >
                      <Upload className="w-3 h-3" />
                      <span>Upload to Verify</span>
                    </button>

                    {doc.required && (
                      <span className="text-[10px] font-bold text-error bg-error-container/60 px-2 py-0.5 rounded-full">
                        Mandatory
                      </span>
                    )}
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* Footer Action */}
        <div className="pt-2 flex justify-between items-center border-t border-outline-variant/40">
          <button
            onClick={onClose}
            className="py-2.5 px-5 bg-surface-container-high hover:bg-surface-container text-on-surface font-bold text-xs rounded-xl transition-all cursor-pointer"
          >
            Close
          </button>

          <a
            href={scheme.officialUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="py-3 px-6 bg-primary hover:bg-primary-container text-white font-bold text-xs rounded-xl shadow-md flex items-center gap-2 transition-all cursor-pointer"
          >
            <span>{t.officialPortal}</span>
            <ExternalLink className="w-4 h-4" />
          </a>
        </div>

      </div>
    </div>
  );
}
